# 5.1 UNIVARIATE PORTFOLIO ANALYSIS

## 5.1.7 Analyzing Returns

In [1]:
# -*- coding:utf-8 -*-
import pandas as pd
import numpy as np
from scipy import stats
import os
import datetime
import statsmodels.formula.api as smf
from dateutil.parser import parse
import statsmodels.api as sm
os.chdir(r'E:\python3\Empirial_Asset_Pricing')
path = os.getcwd()

In [3]:
# 为什么要读取月度因子数据并计算年度的因子值？
# 因为回归是用年度数据

# 读取月度因子数据
factor_monthly = pd.read_csv('data/F-F_Year_Factors.csv')
factor_monthly['dateff'] = factor_monthly['dateff'].apply(int).apply(str).apply(parse)
factor_monthly = factor_monthly[(factor_monthly['dateff'] >= datetime.datetime(1987, 12, 31, 0, 0))&(factor_monthly['dateff'] <= datetime.datetime(2013, 1, 1, 0, 0))]
factor_monthly.rename(columns = {'dateff':'month','mktrf':'mkt'},inplace = True)
factor_monthly = factor_monthly[['month','mkt','smb','hml','umd']]

# 由于常用因子值也为根据变量值分组投资组合的收益率，因此将月度数据按年度连乘(+1后)计算年度因子值
factor_yearly = factor_monthly.copy()
factor_yearly['year'] = factor_yearly['month'].apply(lambda x:x.year)
factor_yearly[['mkt','smb','hml','umd']] = factor_yearly[['mkt','smb','hml','umd']].applymap(lambda x:x+1)
factor_yearly = factor_yearly.groupby('year').prod()
factor_yearly = factor_yearly.applymap(lambda x:(x-1)*100)
factor_yearly = factor_yearly.reset_index()

# 由于个股数据表中中汇报的收益率为t+1期，故此处年份减1使因子值也为t+1期，便于后面连接
factor_yearly_yearlag1 = factor_yearly.copy()
factor_yearly_yearlag1['year'] = factor_yearly_yearlag1['year']-1

In [31]:
# factor_monthly
# factor_yearly

单变量组合分析流程

In [21]:
# 读取个股数据
all_data = pd.read_csv(os.path.join(path,'data','alldata_mktcap.csv'),index_col=0)
all_data = all_data.drop_duplicates(subset=['permno','year'])
all_data = all_data[['permno', 'year', 'beta', 'rt+1', 'bm','mktcap']]

# 分别提取不同变量所需分组数据至多个dataframe
proxy_name_list = ['beta','mktcap','bm']
def select_proxy(proxy_name_list):
    for proxy_name in proxy_name_list:
        globals()[proxy_name] = all_data[['permno', 'year','rt+1',proxy_name]]
select_proxy(proxy_name_list)

## 做等权重的7分组
# 根据bm,beta,mktcap分别进行单变量7分组
def mutate_group(proxy_name_list):
    for proxy_name in proxy_name_list:
        globals()[proxy_name] = globals()[proxy_name].dropna()

        quantiles_proxy = globals()[proxy_name].groupby('year')[proxy_name].describe(
        percentiles=[0.1,0.2,0.4,0.6,0.8,0.9]).reset_index()[['year','10%','20%','40%','60%','80%','90%']]

        df= pd.merge(globals()[proxy_name], quantiles_proxy, how = 'left', on = 'year')

        globals()[proxy_name]['group'] = np.select([df[proxy_name] <= df['10%'],
                           (df[proxy_name] > df['10%']) & (df[proxy_name] <= df['20%']),
                           (df[proxy_name] > df['20%']) & (df[proxy_name] <= df['40%']),
                            (df[proxy_name] > df['40%']) & (df[proxy_name] <= df['60%']),
                            (df[proxy_name] > df['60%']) & (df[proxy_name] <= df['80%']),
                            (df[proxy_name] > df['80%']) & (df[proxy_name] <= df['90%']),
                           (df[proxy_name] > df['90%'])],
                           ['1','2','3','4','5','6','7'])
mutate_group(proxy_name_list)

# 计算等权投资组合收益率
def portfolio_ret(proxy_name_list):
    for proxy_name in proxy_name_list:
        globals()[proxy_name] = globals()[proxy_name].dropna()

        globals()[proxy_name] = globals()[proxy_name].groupby(['group', 'year']).apply(
            lambda x: np.average(x['rt+1'], weights=None)).reset_index()
        globals()[proxy_name].rename(columns={0: 'ret_excess'}, inplace=True)
        globals()[proxy_name] = pd.pivot(globals()[proxy_name], index='year', columns='group')[
            'ret_excess'].reset_index()

        # 没有股票的组用0填充,此算例中数据分布基本均匀且无明显缺失，应用不到
        globals()[proxy_name].replace(np.nan,0,inplace = True)

        globals()[proxy_name]['7-1'] = globals()[proxy_name]['7'] - globals()[proxy_name]['1']
portfolio_ret(proxy_name_list)

# 定义NW调整函数
def nw_adjust(df, group, lags=6):
    df.dropna(subset = [group], inplace = True)
    adj_a = np.array(df[group])
    # 对常数回归
    model = sm.OLS(adj_a, [1] * len(adj_a)).fit(cov_type='HAC', cov_kwds={'maxlags': lags})
    return adj_a.mean().round(2), format(float(model.tvalues), ".2f"),float(model.bse) #第三个参数为系数标准差，此处用不上

In [27]:
beta

group,year,1,2,3,4,5,6,7,7-1
0,1988,2.056380,4.164232,0.791787,6.624564,5.063943,11.612504,6.993541,4.937161
1,1989,-29.117082,-28.754989,-30.076989,-30.660494,-27.934253,-28.828602,-27.870108,1.246975
2,1990,63.915076,26.380233,39.830717,44.794099,54.507938,66.484279,69.634843,5.719767
3,1991,55.409561,40.682731,31.323794,22.695159,16.901347,20.702352,20.408553,-35.001008
4,1992,39.654980,25.564578,26.084669,24.106380,18.801966,16.036788,8.213321,-31.441659
5,1993,-4.633713,-6.005979,-4.790344,-4.031287,-7.454930,-11.473790,-6.259920,-1.626206
6,1994,29.409340,26.120297,25.178768,31.340729,27.845137,28.080430,35.718033,6.308693
7,1995,21.639164,17.039824,19.452752,14.398313,12.892933,11.256496,6.462588,-15.176575
8,1996,32.194204,35.624337,29.761401,21.405115,18.599912,5.780265,-9.473833,-41.668037
9,1997,-5.428176,-10.140421,-8.900338,-11.674966,-4.347672,-8.108821,0.882446,6.310623
10,1998,14.043887,11.284971,20.776237,24.420171,42.440295,73.834315,101.298615,87.254728
11,1999,-16.500353,-2.250398,-5.428766,-1.178819,-1.873689,-13.747644,-34.259535,-17.759182
12,2000,37.834760,28.876455,27.609872,30.718431,25.660304,-0.079571,-21.936463,-59.771223
13,2001,14.170248,11.632808,0.698720,-8.641897,-22.526323,-34.612901,-53.795306,-67.965554
14,2002,86.458959,73.709616,93.748284,63.960496,67.079362,81.537236,94.791713,8.332754
15,2003,29.861897,25.575088,26.919348,21.902914,15.627402,12.674495,-0.087877,-29.949774
16,2004,9.285759,4.103759,5.103733,3.342985,3.470477,-2.888917,-7.893938,-17.179696
17,2005,11.355608,16.722386,13.268570,9.850551,7.983029,13.079683,11.321055,-0.034554
18,2006,-16.258148,-10.690889,-9.454775,-9.041533,-6.370627,-6.518113,-5.284442,10.973707
19,2007,-45.580049,-49.348157,-43.086700,-42.653811,-41.715195,-45.525280,-44.870879,0.709170
20,2008,66.084416,79.710586,67.712035,54.638060,56.237370,60.491043,83.631233,17.546817
21,2009,19.750244,20.430223,22.756560,25.061014,30.935902,32.364160,38.334235,18.583991
22,2010,-4.548624,-5.025515,-1.834676,-5.493845,-7.676481,-15.366932,-17.726260,-13.177635
23,2011,28.377959,25.282724,17.013239,17.606558,16.006904,18.574718,17.270095,-11.107864

TABLE 5.8: Average Returns of Portfolios Sorted on 𝜷, MktCap, and BM

In [13]:
# generate table8
table8_index = ['Beta','','MKtCap','','BM','']
table8_columns = ['1','2','3','4','5','6','7','7-1']
table8 = pd.DataFrame(index = table8_index, columns = table8_columns)
table8.columns.name = 'Sort Variable'
def generate_table8(proxy_name_list):
    for i in range(len(proxy_name_list)):
        for j in range(len(table8_columns)):
            table8.iloc[2*i,j] = nw_adjust(globals()[proxy_name_list[i]], table8_columns[j])[0]
            table8.iloc[2*i+1,j] = nw_adjust(globals()[proxy_name_list[i]],table8_columns[j])[1]
generate_table8(proxy_name_list)
table8

Sort Variable      1      2      3      4      5      6      7    7-1
Beta           18.31  15.03  15.19  12.65  12.51  11.89  11.06  -7.25
                4.75   5.27   4.95   5.04   5.23   4.64   3.20  -1.62
MKtCap         37.51  17.51  12.14   9.62   8.01   8.37   7.98 -29.53
                6.99   4.37   3.78   4.00   4.48   4.33   3.78  -5.58
BM             10.52   7.22   8.13  10.57  14.05  18.88  34.75  24.23
                3.44   3.10   4.23   5.27   5.65   5.51   5.67   4.75

TABLE 5.9: 𝜷-Sorted Portfolio Risk-Adjusted Results

Capital Asset Pricing Model (CAPM) of Sharpe (1964), Lintner (1965), and Mossin (1966)

$r_{p, t}=\alpha+\beta_{M K T} M K T_{t}+\epsilon_{t}$

Fama and French (FF) three-factor model,Fama and French (1993)

$r_{p, t}=\alpha+\beta_{M K T} M K T_{t}+\beta_{S M B} S M B_{t}+\beta_{H M L} H M L_{t}+\epsilon_{t}$

Fama, French, and Carhart (FFC) four-factor model,Jegadeesh and Titman (1993) and Carhart (1997)

$\begin{aligned} r_{p, t}=& \alpha+\beta_{M K T} M K T_{t}+\beta_{S M B} S M B_{t} +\beta_{H M L} H M L_{t}+\beta_{M O M} M O M_{t}+\epsilon_{t} \end{aligned}$

In [10]:
# generate table9
table9_index = ['Excess return','',
                'CAPM','','','',
                'FF','','','','','','','',
                'FFC','','','','','','','','','']
table9_columns = ['Coefficient','1','2','3','4','5','6','7','7-1']
table9 = pd.DataFrame(index = table9_index, columns = table9_columns)
table9.columns.name = 'Model'
table9['Coefficient'] = ['Excess return','',
                         'alpha','','MKT','',
                         'alpha','','MKT','','SMB','','HML','',
                         'alpha','','MKT','','SMB','','HML','','MOM','']

# 连接因子模型因子数据
# 起初在根据年份连接时未如前所述在因子表中将年份减一，导致实际用t期因子值解释t+1期收益，无解释力，
# 因子模型解释后alpha反变大，现已修正
def mutate_factor(proxy_name_list):
    for proxy_name in proxy_name_list:
        globals()[proxy_name] = pd.merge(globals()[proxy_name], factor_yearly_yearlag1, how='left', on=['year'])
mutate_factor(proxy_name_list)

# 定义用于风险调整的CAPM,FF3,FFC因子模型函数
def capm_adjust(df, group, lags = 6):
    df.dropna(subset = [group,'mkt'], inplace = True)
    x = sm.add_constant(df['mkt'])
    y = df[group]
    model = sm.OLS(y, x).fit(cov_type='HAC', cov_kwds={'maxlags': lags})
    return model

def ff3_adjust(df, group, lags = 6):
    df.dropna(subset=[group, 'mkt', 'smb', 'hml'], inplace = True)
    x = sm.add_constant(df[['mkt', 'smb', 'hml']])
    y = df[group]
    model = sm.OLS(y, x).fit(cov_type='HAC', cov_kwds={'maxlags': lags})
    return model

def ffc_adjust(df, group, lags = 6):
    df.dropna(subset=[group, 'mkt', 'smb', 'hml', 'umd'], inplace = True)
    x = sm.add_constant(df[['mkt', 'smb', 'hml','umd']])
    y = df[group]
    model = sm.OLS(y, x).fit(cov_type='HAC', cov_kwds={'maxlags': lags})
    return model

# 分别计算不同因子模型调整后的风险收益及t值
def generate_table9():
    for j in range(len(table9.columns) - 1):
        table9.iloc[0,j+1] = nw_adjust(globals()['beta'], table9_columns[j+1])[0]
        table9.iloc[1,j+1] = nw_adjust(globals()['beta'], table9_columns[j+1])[1]

        for i in range(2):
            table9.iloc[2+2*i, j+1] = capm_adjust(globals()['beta'], table9_columns[j+1]).params[i].round(2)
            table9.iloc[3+2*i, j+1] = capm_adjust(globals()['beta'], table9_columns[j+1]).tvalues[i].round(2)

        for i in range(4):
            table9.iloc[6+2*i, j+1] = ff3_adjust(globals()['beta'], table9_columns[j+1]).params[i].round(2)
            table9.iloc[7+2*i, j+1] = ff3_adjust(globals()['beta'], table9_columns[j+1]).tvalues[i].round(2)

        for i in range(5):
            table9.iloc[14+2*i, j+1] = ffc_adjust(globals()['beta'], table9_columns[j+1]).params[i].round(2)
            table9.iloc[15+2*i, j+1] = ffc_adjust(globals()['beta'], table9_columns[j+1]).tvalues[i].round(2)
generate_table9()
table9

Model,Coefficient,1,2,3,4,5,6,7,7-1
Excess return,Excess return,18.31,15.03,15.19,12.65,12.51,11.89,11.06,-7.25
,,4.75,5.27,4.95,5.04,5.23,4.64,3.20,-1.62
CAPM,alpha,9.77,7.27,6.88,5.02,3.94,0.93,-2.44,-12.21
,,1.96,1.51,1.53,1.28,1.15,0.38,-0.97,-2
,MKT,1.15,1.05,1.12,1.03,1.16,1.48,1.82,0.67
,,3.99,3.1,4.42,4.17,5.83,8.73,8.38,1.83
FF,alpha,4.59,2.2,2.5,1.31,1.42,-0.17,-1.19,-5.79
,,1.72,1.37,2.18,1.01,1.02,-0.09,-0.52,-1.69
,MKT,1.24,1.16,1.18,1.08,1.15,1.39,1.62,0.38
,,9.52,5.73,9.36,10.18,14.16,16.21,10.93,1.73
,SMB,1.67,1.26,1.53,1.32,1.4,1.64,1.82,0.15
,,8.52,6.92,7.17,11.58,23.03,11.41,9.4,0.45
,HML,0.68,0.76,0.54,0.46,0.18,-0.19,-0.73,-1.42
,,6.19,12.5,6.42,5.23,1.43,-1.47,-4.31,-5.77
FFC,alpha,7.55,8.53,7.01,3.48,2.85,-0.59,0.39,-7.15
,,3,5.64,4.74,2.59,2.28,-0.34,0.12,-1.51
,MKT,1.15,0.98,1.06,1.02,1.11,1.4,1.57,0.42
,,9.82,8.24,12.97,11.48,19.15,17.15,9.65,1.58
,SMB,1.5,0.91,1.28,1.2,1.32,1.66,1.73,0.23
,,5.77,3.66,5.51,8.86,13.87,8.06,6.9,0.58
,HML,0.62,0.63,0.45,0.41,0.15,-0.18,-0.77,-1.39
,,4.65,6.84,8.67,6.48,1.29,-1.38,-4.74,-5.66
,MOM,-0.24,-0.51,-0.36,-0.17,-0.11,0.03,-0.13,0.11
,,-1.99,-3.46,-5.71,-3.08,-1.87,0.23,-0.52,0.38

# 5.2 BIVARIATE INDEPENDENT-SORT ANALYSIS

## 5.2.1 Breakpoints

Letting $n_{P 1}$ represent the number of groups that will be created based on the firs sort variable and $n_{P 2}$ be the number of groups that will be created based on the second sort variable, the number of portfolios that will be formed is $n_{P 1} \times n_{P 2}$. There are therefore $n_{P 1}$ and $n_{P 2}$ breakpoints for the first and second sort variables, respectively.

The breakpoints for each of the two sort variables are calculated in exactly the same way as for a univariate portfolio analysis. The breakpoints (percentiles used to calculate the breakpoints) used to form the groups for the first sort variable are denoted $B 1_{j, t}\left(p 1_{j}\right)$ for $j \in\left\{1,2, \ldots, n_{P 1}-1\right\}$, and the breakpoints (percentiles) for the second sort variable are $B 2_{k, t}\left(p 2_{k}\right)$ for $k \in\left\{1,2, \ldots, n_{P 2}-1\right\}$. The actual breakpoints are calculated as

$B 1_{j, t}=\operatorname{Pctl}_{p 1_{j}}\left(\left\{X 1_{t}\right\}\right)$

$B 2_{k, t}=\operatorname{Pctl}_{p 2_{k}}\left(\left\{X 2_{t}\right\}\right)$

where $\operatorname{Pctl}_{p}(Z)$ is the $p$ th percentile of the set $Z$ and $\left\{X 1_{t}\right\}$ and $\left\{X 2_{t}\right\}$ are the set of available values of $X 1$ and $X 2$, respectively, in period $t$.

TABLE 5.10: Bivariate Independent-Sort Breakpoints

In [33]:
# generate table10
# bivariate independent-sort portfolio，
# The first sort variable is beta and the second sort variable is MktCap；
def generate_table10():
    quantiles_proxy_beta = all_data.groupby('year')['beta'].describe(
            percentiles=[0.3, 0.7]).reset_index()[['year', '30%', '70%']]

    quantiles_proxy_mktcap = all_data.groupby('year')['mktcap'].describe(
            percentiles=[0.25, 0.5, 0.75]).reset_index()[['year', '25%', '50%', '75%']]

    beta_mktcap_group = pd.merge(quantiles_proxy_beta, quantiles_proxy_mktcap, on=['year'])
    beta_mktcap_group.rename(columns = {'30%':'B1_1t','70%':'B1_2t',
                                        '25%':'B2_1t','50%':'B2_2t','75%':'B2_3t'},inplace=True)
    return beta_mktcap_group
table10 = generate_table10()
table10.iloc[:,1:] = table10.iloc[:,1:].applymap(lambda x:round(x,2))
table10

    year  B1_1t  B1_2t   B2_1t   B2_2t    B2_3t
0   1988   0.17   0.63    9.37   33.07   147.86
1   1989   0.16   0.68    9.60   35.31   172.48
2   1990   0.22   0.86    6.44   24.64   138.18
3   1991   0.24   0.85   10.35   42.60   214.53
4   1992   0.25   0.97   16.60   62.18   271.99
5   1993   0.29   0.93   22.38   73.77   300.51
6   1994   0.36   0.97   20.32   67.88   273.62
7   1995   0.26   0.90   25.84   89.30   356.89
8   1996   0.33   0.92   28.61   97.40   403.78
9   1997   0.25   0.73   33.19  116.20   485.42
10  1998   0.40   0.94   29.26  105.26   495.17
11  1999   0.15   0.52   36.96  141.90   689.32
12  2000   0.25   0.86   25.31  105.73   585.34
13  2001   0.34   0.97   34.32  142.76   717.57
14  2002   0.32   0.89   33.29  130.18   621.07
15  2003   0.38   0.97   70.18  267.36  1003.43
16  2004   0.63   1.34   92.15  322.98  1234.88
17  2005   0.58   1.28   94.98  336.23  1313.29
18  2006   0.61   1.40  108.21  395.78  1523.69
19  2007   0.55   1.17   94.36  345.08  1417.56
20  2008   0.56   1.13   38.34  194.47   869.96
21  2009   0.64   1.45   70.47  303.23  1320.71
22  2010   0.76   1.32   95.59  406.07  1774.81
23  2011   0.80   1.37   82.21  390.77  1724.61
24  2012   0.75   1.31  105.13  478.82  1972.96

## 5.2.2 Portfolio Formation

As with the univariate portfolio analysis, the next step in bivariate portfolio analysis is to form the periodic portfolios. As mentioned earlier, if there are $n_{P 1}$ groups based on the first sort variable $X 1$ and $n_{P 2}$ groups based on the second sort variable $X 2$, then there will be $n_{P 1} \times n_{P 2}$ portfolios each time period. The portfolios for period $t$ are denoted $P_{j, k, t}$, where the first subscript indicates the group of the first sort variable and the second subscript indicates that of the second sort variable. In general, the portfolios are defined as

$P_{j, k, t}=\left\{i \mid B 1_{j-1, t} \leq X 1_{i, t} \leq B 1_{j, t}\right\} \cap\left\{i \mid B 2_{k-1, t} \leq X 2_{i, t} \leq B 2_{k, t}\right\}$

for $j \in\left\{1,2, \ldots, n_{P 1}\right\}, \quad k \in\left\{1,2, \ldots, n_{P 2}\right\}, \quad$ where $\quad B 1_{0, t}=B 2_{0, t}=-\infty$,
$B 1_{n_{p 1}, t}=B 2_{n_{p 2, t}}=\infty$, and $\cap$ is the intersection operator. Thus, for a given entity $i$ to be held in portfolio $P_{j, k, t}$, the entity must have a value of $X 1$ in period $t$ that is between the $j-1$ st and $j$ th (inclusive) period $t$ breakpoints for the first sort variable, and also have a period $t$ value of $X 2$ between the $k-1$ st and $k$ th (inclusive) period $t$ breakpoints for the second sort variable.

TABLE 5.11: Bivariate Independent-Sort Number of Stocks per Portfolio

In [16]:
# generate table11
all_data_and_breakpoints = pd.merge(all_data,table10,on='year')
def portfolio_ind_3x4():
    df = all_data_and_breakpoints.copy()
    df = df.dropna(subset=['beta','mktcap'])
    df['X1_group'] = np.select([
        (df['beta'] < df['B1_1t']),
        (df['beta'] >= df['B1_1t']) & (df['beta'] < df['B1_2t']),
        (df['beta'] >= df['B1_2t'])],
        ['1','2','3'])
    df['X2_group'] = np.select([
        (df['mktcap'] < df['B2_1t']),
        (df['mktcap'] >= df['B2_1t']) & (df['mktcap'] < df['B2_2t']),
        (df['mktcap'] >= df['B2_2t']) & (df['mktcap'] < df['B2_3t']),
        (df['mktcap'] >= df['B2_3t'])],
        ['1','2','3','4'])
    return df[['permno','year','beta','rt+1','mktcap','X1_group','X2_group']]
all_data_and_groups = portfolio_ind_3x4()

def generate_table11(group_table):
    n = group_table.groupby(['year', 'X1_group', 'X2_group'])['permno'].count().reset_index().rename(
            columns={'permno': 'n_firms'})
    df = pd.pivot_table(n, index=['year', 'X2_group'], columns='X1_group')['n_firms'].reset_index()
    df.rename(columns={'1':'beta1','2':'beta2','3':'beta3'},inplace=True)
    return df
table11 = generate_table11(all_data_and_groups)
table11

X1_group  year X2_group  beta1  beta2  beta3
0         1988        1    702    473    220
1         1988        2    537    562    290
2         1988        3    337    693    399
3         1988        4    108    545    823
4         1989        1    734    420    216
..         ...      ...    ...    ...    ...
95        2011        4    169    541    224
96        2012        1    656    152     72
97        2012        2    135    393    350
98        2012        3     72    447    361
99        2012        4    178    434    290

[100 rows x 5 columns]

![title](table12.png)

TABLE 5.13: Bivariate Independent-Sort Portfolio Excess Returns

In [18]:
# generate table13
def avg_r(group_table):
    ewret = group_table.groupby(['year','X2_group','X1_group'])['rt+1'].mean().reset_index()
    df = pd.pivot_table(ewret,index=['year','X2_group'],columns='X1_group')['rt+1'].reset_index()
    df['diff'] = df['3']-df['1']
    df['avg'] = (df['1']+df['2']+df['3'])/3
    df.loc[:,'1':'avg']= df.loc[:,'1':'avg'].applymap(lambda x:round(x,2))
    return df
table13 = avg_r(all_data_and_groups)

def get_diff(table):
    X = pd.DataFrame()
    for i in range(1988,2012):
        x = table[table['year']==i]
        x1 = pd.DataFrame(columns=x.columns,index=list(range(2)))
        x1['year'] = [i,i]
        x1.iloc[0,1] = ['mktcap_diff']
        x1.iloc[1,1] = ['mktcap_avg']
        x1.iloc[0, 2:] = (x.iloc[3, 2:] - x.iloc[0, 2:]).apply(lambda x:round(x,2))
        x1.iloc[1, 2:] = x.iloc[0:3, 2:].mean().apply(lambda x:round(x,2))
        X = pd.concat([X, x])
        X = pd.concat([X, x1])
    return X
table13 = get_diff(table13)
table13 = table13.reset_index(drop= True)
table13

X1_group  year     X2_group      1      2      3   diff    avg
0         1988            1   4.37   3.94   8.64   4.27   5.65
1         1988            2  -0.71  -2.49 -10.81  -10.1  -4.67
2         1988            3  -0.17   3.94   3.48   3.65   2.42
3         1988            4   5.25  15.04  15.69  10.45  11.99
4         1988  mktcap_diff   0.88   11.1   7.05   6.18   6.34
..         ...          ...    ...    ...    ...    ...    ...
139       2011            2  25.88  18.91  18.02  -7.85  20.94
140       2011            3  11.27  15.19  19.51   8.24  15.32
141       2011            4  11.83  17.54  17.24   5.41  15.54
142       2011  mktcap_diff -16.71   5.62  24.43  41.14   4.45
143       2011   mktcap_avg   21.9  15.34  10.11 -11.78  15.78

[144 rows x 7 columns]

TABLE 5.14: Bivariate Independent-Sort Portfolio Excess and Abnormal Returns

In [20]:
# generate table14
##计算综合excess return和FFC调整alpha
table14_sub_index = ['Excess return','','FFC alpha','']
table14_sub_column = ['beta1','beta2','beta3','beta Diff','beta Avg']
table14_sub = pd.DataFrame(index=table14_sub_index,columns=table14_sub_column)
subs = table13['X2_group'].unique()

def generate_table14_subs():
    for sub in subs:
        globals()[sub + '_table'] = table14_sub.copy()
        globals()[sub + '_data'] = table13[table13['X2_group']==sub].copy()
        globals()[sub + '_data'].loc[:,'1':'avg'] = globals()[sub + '_data'].loc[:,'1':'avg'].applymap(lambda x:np.float64(x))
        globals()[sub + '_data'] = pd.merge(globals()[sub + '_data'],factor_yearly_yearlag1,on='year')
        for i in range(len(globals()[sub + '_table'].columns)):
            globals()[sub + '_table'].iloc[0,i] = nw_adjust(globals()[sub + '_data'],globals()[sub + '_data'].columns[2+i])[0]
            globals()[sub + '_table'].iloc[1,i] = nw_adjust(globals()[sub + '_data'],globals()[sub + '_data'].columns[2+i])[1]
            globals()[sub + '_table'].iloc[2,i] = ffc_adjust(globals()[sub + '_data'],globals()[sub + '_data'].columns[2+i]).params[0].round(2)
            globals()[sub + '_table'].iloc[3,i] = ffc_adjust(globals()[sub + '_data'],globals()[sub + '_data'].columns[2+i]).tvalues[0].round(2)
generate_table14_subs()

table14 = pd.DataFrame()
for sub in subs:
    table14 = pd.concat([table14, globals()[sub + '_table']])
table14 = table14.reset_index().reset_index()
table14['level_0'] = ['MktCap 1','','','',
                'MktCap 2', '', '', '',
                'MktCap 3', '', '', '',
                'MktCap 4', '', '', '',
                'MktCap Diff', '', '', '',
                'MktCap Avg', '', '', '',]
table14.rename(columns={'index':'Coefficient',
                        'level_0':''},inplace=True)
table14

                   Coefficient  beta1  beta2  beta3 beta Diff beta Avg
0      MktCap 1  Excess return  24.73  31.06  36.03      11.3    30.61
1                                5.78   5.78   4.12      1.84     5.38
2                    FFC alpha  15.35  27.32  24.83      9.48     22.5
3                                4.93   6.51   2.97       1.5     4.91
4      MktCap 2  Excess return  10.73  13.84  13.77      3.05    12.78
5                                3.50   3.30   4.18      0.95     4.09
6                    FFC alpha  -0.29   1.38   2.44      2.73     1.17
7                               -0.14   0.37   0.95      0.69     0.66
8      MktCap 3  Excess return   7.76   9.86   8.03      0.27     8.55
9                                2.63   4.29   3.60      0.08     4.05
10                   FFC alpha  -1.17   0.72  -2.43     -1.26    -0.96
11                              -0.41   0.64  -2.08     -0.32    -0.99
12     MktCap 4  Excess return    5.7   8.58   8.19      2.49     7.49
13                               3.20   5.62   3.17      1.01     4.44
14                   FFC alpha  -1.64   1.62  -2.09     -0.45     -0.7
15                              -1.13   2.12  -1.24     -0.17    -1.01
16  MktCap Diff  Excess return -19.03 -22.48 -27.84     -8.81   -23.12
17                              -5.24  -4.41  -3.13     -1.39    -4.21
18                   FFC alpha -16.99 -25.69 -26.92     -9.93    -23.2
19                              -4.03   -6.2   -3.5      -2.4    -4.79
20   MktCap Avg  Excess return   14.4  18.25  19.28      4.87    17.31
21                               4.37   5.15   4.50      1.45     5.04
22                   FFC alpha   4.63    9.8   8.28      3.65     7.57
23                               1.98   4.86   2.28      0.89     3.65